[stage]
gray_adc_upper_threshold = 2900
gray_io_off_stage_case_value = 0

[edge]
lower_threshold = [ 1800, 1750, 1750, 1800,]
upper_threshold = [ 2100, 2270, 2270, 2100,]
fallback_speed = 3200
fallback_duration = 0.3
advance_speed = 3200
advance_duration = 0.35
turn_speed = 2000
full_turn_duration = 0.45
half_turn_duration = 0.225
turn_left_prob = 0.5
drift_speed = 3000
drift_duration = 0.18

[surrounding]
io_encounter_object_value = 0
left_adc_lower_threshold = 1300
right_adc_lower_threshold = 1300
front_adc_lower_threshold = 1300
back_adc_lower_threshold = 1500
atk_break_front_lower_threshold = 1700
atk_break_use_edge_sensors = true
atk_speed_enemy_car = 2300
atk_speed_enemy_box = 1600
atk_speed_neutral_box = 1300
fallback_speed_ally_box = 2000
fallback_speed_edge = 3000
atk_enemy_car_duration = 6.0
atk_enemy_box_duration = 6.0
atk_neutral_box_duration = 6.0
fallback_duration_ally_box = 0.2
fallback_duration_edge = 0.2
turn_speed = 2820
turn_left_prob = 0.5
rand_turn_speeds = [ 2000, 2500,]
rand_turn_speed_weights = [ 3, 1,]
full_turn_duration = 0.45
half_turn_duration = 0.225

[search]
use_gradient_move = true
gradient_move_weight = 20
use_scan_move = true
scan_move_weight = 2
use_rand_turn = false
rand_turn_weight = 0

[fence]
front_adc_lower_threshold = 1200
rear_adc_lower_threshold = 1300
left_adc_lower_threshold = 1300
right_adc_lower_threshold = 1300
io_encounter_fence_value = 0
max_yaw_tolerance = 20.0
stage_align_speed = 1000
max_stage_align_duration = 4.5
stage_align_direction = "rand"
direction_align_speed = 600
max_direction_align_duration = 5.5
direction_align_direction = "rand"
exit_corner_speed = 1950
max_exit_corner_duration = 2.0

[boot]
button_io_activate_case_value = 0
time_to_stabilize = 0.1
max_holding_duration = 180.0
left_threshold = 1100
right_threshold = 1100
dash_speed = 8000
dash_duration = 0.2
turn_speed = 3000
full_turn_duration = 0.45
turn_left_prob = 0.5

[backstage]
time_to_stabilize = 0.1
small_advance_speed = 2000
small_advance_duration = 0.3
dash_speed = 7500
dash_duration = 0.35
turn_speed = 5000
full_turn_duration = 0.35
turn_left_prob = 0.5

[strategy]
use_edge_component = true
use_surrounding_component = true
use_normal_component =true
use_fence_component = true

[perf]
checking_duration = 0.0

[search.gradient_move]
max_speed = 3500
min_speed = 1600
lower_bound = 3000
upper_bound = 3800

[search.scan_move]
front_max_tolerance = 1000
rear_max_tolerance = 1300
left_max_tolerance = 1000
right_max_tolerance = 1000
io_encounter_object_value = 0
scan_speed = 300
scan_duration = 4.5
scan_turn_left_prob = 0.5
fall_back_speed = 1500
fall_back_duration = 0.2
turn_speed = 5000
turn_left_prob = 0.5
full_turn_duration = 0.45
half_turn_duration = 0.225

[search.rand_turn]
turn_speed = 5000
turn_left_prob = 0.5
full_turn_duration = 0.45
half_turn_duration = 0.225

[fence.rand_walk]
use_straight = true
straight_weight = 3
rand_straight_speeds = [ 1300, 1600,]
rand_straight_speed_weights = [ 1, 3,]
use_turn = true
turn_weight = 1
rand_turn_speeds = [ 3000, 5000,]
rand_turn_speed_weights = [ 1, 3,]
walk_duration = 0.5
