[motion]
motor_fr = [ 2, 1,]
motor_fl = [ 4, -1,]
motor_rr = [ 1, 1,]
motor_rl = [ 3, -1,]
port = "/dev/ttyUSB0"

[vision]
team_color = "blue"
use_camera = true
camera_device_id = 0

[logger]
log_level = "DEBUG"

[sensor]
adc_min_sample_interval = 5
edge_fl_index = 8
edge_fr_index = 1
edge_rl_index = 7
edge_rr_index = 0
left_adc_index = 3
right_adc_index = 5
front_adc_index = 6
rb_adc_index = 4
gray_adc_index = 2
gray_io_off_stage_case = 0
gray_io_left_index = 6
gray_io_right_index = 5
fl_io_index = 7
fr_io_index = 4
rl_io_index = 3
rr_io_index = 2
