
[motion]
motor_fr = [ 2, 1,]
motor_fl = [ 4, -1,]
motor_rr = [ 1, 1,]
motor_rl = [ 3, -1,]
port = "/dev/ttyUSB0"

[vision]
team_color = "blue"
resolution_multiplier = 1.0
use_camera = true
camera_device_id = 0

[logger]
log_level = "INFO"

[sensor]
gyro_fsr = 1000
accel_fsr = 8

reboot_button_index = 6





adc_min_sample_interval = 5
edge_fl_index = 3
edge_fr_index = 0
edge_rl_index = 2
edge_rr_index = 1
left_adc_index = 6
right_adc_index = 4
front_adc_index = 5
rb_adc_index = 7
gray_adc_index = 8
gray_io_off_stage_case = 0
gray_io_left_index = 1
gray_io_right_index = 0
fl_io_index = 5
fr_io_index = 2
rl_io_index = 4
rr_io_index = 3
